.Dd June 04, 2024
.Dt XCALENDAR 1
.Sh NAME
.Nm xcalendar
.Nd simple calendar for X
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.El
.Sh CONTROLS
.Bl -bullet -compact -width indent
.It
goto previous/next month with h/l keys
.It
goto previous/next year with j/k keys
.It
goto current year & month with c key
.It
exit the program with q/escape keys
.El
.Sh EXAMPLES
.Bl -tag -width indent
.It display calendar using Norwegian locale
LANG=nb_NO.UTF-8 xcalendar
.El
.Sh SEE ALSO
.Xr X 7
.Xr cal 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xcalendar/issues
